### ISSUE TITLE
Enable Web SSL: Internal Ansible error on 8.2.4

### ISSUE THREAD

**Issue by T0T4R4** [splunk/docker-splunk#535]
Hi guys,

I am trying to refresh my spluk container with latest 8.2.4 and ansible throws errors related to setting up SSL which I can't understand... Would someone have a clue about what I should do to fix this ?

```TASK [splunk_common : Enable Web SSL] ******************************************
task path: /opt/ansible/roles/splunk_common/tasks/enable_splunkweb_ssl.yml:2
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ini_file_payload_4d4pkul3/ansible_ini_file_payload.zip/ansible/module_utils/basic.py", line 2380, in atomic_move
    os.rename(b_src, b_dest)
OSError: [Errno 18] Invalid cross-device link: b'/home/splunk/.ansible/tmp/ansible-moduletmp-1644218919.1463647-moosi9db/tmpcp9_7c4h' -> b'/opt/splunk/etc/system/local/web.conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_ini_file_payload_4d4pkul3/ansible_ini_file_payload.zip/ansible/module_utils/basic.py", line 2439, in atomic_move
    os.rename(b_tmp_dest_name, b_dest)
OSError: [Errno 16] Device or resource busy: b'/opt/splunk/etc/system/local/.ansible_tmp8xvgai6dweb.conf' -> b'/opt/splunk/etc/system/local/web.conf'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_no_value": false,
            "attributes": null,
            "backup": false,
            "create": true,
            "dest": "/opt/splunk/etc/system/local/web.conf",
            "group": "splunk",
            "mode": 432,
            "no_extra_spaces": false,
            "option": "enableSplunkWebSSL",
            "owner": "splunk",
            "path": "/opt/splunk/etc/system/local/web.conf",
            "section": "settings",
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "state": "present",
            "unsafe_writes": false,
            "value": "0"
        }
    },
    "warnings": [
        "Module remote_tmp /home/splunk/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp dir with the correct permissions manually"
    ]
}

MSG:

Unable to make /home/splunk/.ansible/tmp/ansible-moduletmp-1644218919.1463647-moosi9db/tmpcp9_7c4h into to /opt/splunk/etc/system/local/web.conf, failed final rename from b'/opt/splunk/etc/system/local/.ansible_tmp8xvgai6dweb.conf': [Errno 16] Device or resource busy: b'/opt/splunk/etc/system/local/.ansible_tmp8xvgai6dweb.conf' -> b'/opt/splunk/etc/system/local/web.conf'

PLAY RECAP *********************************************************************
localhost                  : ok=34   changed=0    unreachable=0    failed=1    skipped=41   rescued=0    ignored=0

Monday 07 February 2022  07:28:39 +0000 (0:00:00.283)       0:00:10.453 *******
===============================================================================
splunk_common : Update Splunk directory owner --------------------------- 2.06s
/opt/ansible/roles/splunk_common/tasks/change_splunk_directory_owner.yml:2 ----
Gathering Facts --------------------------------------------------------- 1.28s
/opt/ansible/site.yml:2 -------------------------------------------------------
splunk_common : Update /opt/splunk/etc ---------------------------------- 0.45s
/opt/ansible/roles/splunk_common/tasks/update_etc.yml:7 -----------------------
splunk_common : Check for scloud ---------------------------------------- 0.43s
/opt/ansible/roles/splunk_common/tasks/get_facts.yml:8 ------------------------
splunk_common : Find manifests ------------------------------------------ 0.43s
/opt/ansible/roles/splunk_common/tasks/get_facts.yml:61 -----------------------
splunk_common : Enable splunktcp input ---------------------------------- 0.42s
/opt/ansible/roles/splunk_common/tasks/s2s/configure_splunktcp.yml:2 ----------
splunk_common : Remove splunktcp-ssl input ------------------------------ 0.30s
/opt/ansible/roles/splunk_common/tasks/s2s/configure_splunktcp.yml:12 ---------
splunk_common : Reset root CA ------------------------------------------- 0.30s
/opt/ansible/roles/splunk_common/tasks/s2s/configure_splunktcp.yml:30 ---------
splunk_common : Remove input SSL settings ------------------------------- 0.30s
/opt/ansible/roles/splunk_common/tasks/s2s/configure_splunktcp.yml:21 ---------
splunk_common : Create .ui_login ---------------------------------------- 0.30s
/opt/ansible/roles/splunk_common/tasks/remove_first_login.yml:2 ---------------
splunk_common : Check for existing splunk secret ------------------------ 0.29s
/opt/ansible/roles/splunk_common/tasks/get_facts.yml:42 -----------------------
splunk_common : Check for existing installation ------------------------- 0.28s
/opt/ansible/roles/splunk_common/tasks/get_facts.yml:29 -----------------------
splunk_common : Enable Web SSL ------------------------------------------ 0.28s
/opt/ansible/roles/splunk_common/tasks/enable_splunkweb_ssl.yml:2 -------------
splunk_common : Check if /sbin/updateetc.sh exists ---------------------- 0.28s
/opt/ansible/roles/splunk_common/tasks/update_etc.yml:2 -----------------------
Provision role ---------------------------------------------------------- 0.15s
/opt/ansible/site.yml:22 ------------------------------------------------------
splunk_common : include_tasks ------------------------------------------- 0.10s
/opt/ansible/roles/splunk_common/tasks/main.yml:93 ----------------------------
splunk_common : include_tasks ------------------------------------------- 0.10s
/opt/ansible/roles/splunk_common/tasks/main.yml:51 ----------------------------
splunk_common : include_tasks ------------------------------------------- 0.09s
/opt/ansible/roles/splunk_common/tasks/main.yml:60 ----------------------------
splunk_common : include_tasks ------------------------------------------- 0.08s
/opt/ansible/roles/splunk_common/tasks/main.yml:41 ----------------------------
splunk_common : include_tasks ------------------------------------------- 0.08s
/opt/ansible/roles/splunk_common/tasks/main.yml:10 ----------------------------```

**Comment by T0T4R4** [comment]
I just noticed that in my docker-compose I have defined bindings for the user-prefs and web configuration files, which may disturb ansible...

```
      - type: bind
        source: ./user-prefs.conf
        target: /opt/splunk/etc/system/local/user-prefs.conf
      - type: bind
        source: ./web.conf
        target: /opt/splunk/etc/system/local/web.conf```

**Comment by mcauto** [comment]
> I just noticed that in my docker-compose I have defined bindings for the user-prefs and web configuration files, which may disturb ansible...
> 
> ```
>       - type: bind
>         source: ./user-prefs.conf
>         target: /opt/splunk/etc/system/local/user-prefs.conf
>       - type: bind
>         source: ./web.conf
>         target: /opt/splunk/etc/system/local/web.conf```
> ```


 how to enable ssl?
